### ISSUE TITLE
Build fails on Parcel 2 + pnpm because of stats.js module

### ISSUE THREAD

**Issue by talentlessguy** [react-spring/drei#10]
# Problem

When I try to import `drei` in a Parcel 2 project, like this:

```js
import { OrbitControls } from 'drei'
```

 that's what I get:

![image](https://user-images.githubusercontent.com/35937217/81698681-01c21a00-946f-11ea-80f3-94710719f361.png)

# Solution

I think it's good to generate a bundle with not only `dist/index.js` but each component separately as well. It is possible if Rollup config uses output dir instead of output file. so we will be able to import each component separately without `stats.js` being a direct dependency.

# Versions

* pnpm: `4.14.2`
* drei: `^0.0.32`
* parcel: `^2.0.0-alpha.3.2`

**Comment by drcmda** [comment]
i dont see why this is a bug on rollups or dreis side. https://unpkg.com/browse/drei@0.0.32/dist/index.js

```jsx
import StatsImpl from 'stats.js';

https://unpkg.com/browse/drei@0.0.32/package.json

jsx```
"dependencies": {
  "stats.js": "^0.17.0",


```

**Comment by talentlessguy** [comment]
@drei yeah it is a pnpm issue, it probably didn't link `stats.js` module.

I wanted to import `HTML` with `drei/dist/HTML.js` not to have to deal with missing module errors which I don't use.

I think I will close the issue though, but just in case anyone faces the same issue, the solution is installing `stats.js` directly in the project:

```sh
pnpm i stats.js
```
