### ISSUE TITLE
Request: show example of dashed lines using Line abstraction

### ISSUE THREAD

**Issue by RobRendell** [react-spring/drei#103]
I'm having no luck getting the drei Line abstraction to draw with dashed lines.  I'd love for the example codeSandBox to demo the effect in action, so I can see what I'm doing wrong.

Looking at the source, I can see that drei's version is calling computeLineDistances(), so setting `dashed` to true and `dashScale`, `dashSize` and `gapSize` to sensible values should give the dashed line effect.

(Of course, what those sensible values might be isn't obvious - THREE's doco for the LineDashedMaterial is pretty unhelpful.)

In any case, I'm unable to get the effect to show, either in my own code or by editing the Line example codeSandBox.

**Comment by giulioz** [comment]
It's because it defaults to LineMaterial, not to LineDashedMaterial. I'll try to give the option to change the materials in a next version.

**Comment by RobRendell** [comment]
@giulioz Ah, interesting!  Thanks! So it's a flaw in the current implementation, not in my usage of it :)

If I may suggest something, it seems to me that the existing `dashed` boolean prop that the Line component already takes should select between `LineMaterial` and `LineDashedMaterial`.

**Comment by RobRendell** [comment]
Actually, doing some more reading about this, the `LineMaterial` in Drei's Line abstraction is not the base `THREE.LineMaterial`, it's the one in `three/examples/jsm/lines/LineMaterial`, and it does support `dashed`, as long as you do the hacks outlined here: https://github.com/mrdoob/three.js/blob/22ed6755399fa180ede84bf18ff6cea0ad66f6c0/examples/webgl_lines_fat.html#L236-L239

I've raised a PR implementing this change, and an update to the Line storyboard which shows it in action.

**Comment by RobRendell** [comment]
With the above PR merged, there is now a working example of a dashed Line abstraction in the Storyboard: https://drei.react-spring.io/?path=/story/abstractions-line--vertex-colors-line

Thanks!  Closing this issue.

**Comment by jonybekov** [comment]
Try this
```typescript
import { Line } from "@react-three/drei"

function App() {
   return (
     <Canvas>
           <Line
                lineWidth={0.5}
                worldUnits
                **depthWrite
                dashed**
                dashScale={10}
                points={points}
                color={color}
              />     
     </Canvas>
                    
}
```
