### ISSUE TITLE
Question: How to render Html at certain depth in scene

### ISSUE THREAD

**Issue by RishabhKarnad** [react-spring/drei#107]
I'm trying to implement text banners for 3d objects using `react-three-fiber`.

The `Html` is placed inside a `group`, which contains another `mesh` which is a 3d model to be rendered. The `Html` displays some text associated with the object.

```
<group position={...pos} rotation={...rot}>
    <mesh {...meshProps} />
    <Html>
        <p>The name of the object</p>
    </Html>
</group>
```

Is there any way to render `Html` in such a way that it will be displayed behind other 3d objects if the mesh associated with it is obstructed by another object in the scene. Basically, it should behave like a sprite banner, but we need Html since it's easier to style and make accessible.

We have looked into using Raycasters to do this, but is there any simpler way to accomplish it?

**Comment by drcmda** [comment]
html displays either on top of your canvas or below (with the `prepend` flag). but these are still two separate worlds, the dom and webgl. html elements can have zindex of course, specifically if you provide a `scaleFactor`, but they can't be occluded by 3d content. <- if that's what you need and it's just about plain text then use drei's `<Text />` component, that one is rendered in the shader.

**Comment by RishabhKarnad** [comment]
@drcmda Thanks for the quick reply. Some things we've been struggling with while using `Text` and sprites are:
- Accessibility (keyboard focus)
- Autoscaling to maintain the text size even when the user zooms out with a dolly cam

It's not very clear from the drei and troika-three-text docs whether these are supported.

**Comment by drcmda** [comment]
webgl is not accessible, the spec isn't at least. it's completely up to userland to solve it unfortunately, for instance through invisible html overlays etc. html can work, but it's not part of the 3d space at all.

**Comment by mattrossman** [comment]
@drcmda Is there interest/plans in having a component that brings 2D page elements into the 3D space, a la [three-web-layer](https://github.com/aelatgt/three-web-layer) or [web2vr](https://github.com/kikoano/web2vr)?

**Comment by drcmda** [comment]
you can use these two, if they work.

**Comment by RishabhKarnad** [comment]
Thanks. I'll look into the options mentioned by @mattrossman too. Closing this for now.
