### ISSUE TITLE
In OrbitControls' typing all properties are required?

### ISSUE THREAD

**Issue by juuyan** [react-spring/drei#113]
I get the following warning when using OrbitControls helper in TS
![image](https://user-images.githubusercontent.com/48427014/92303924-1c834600-efac-11ea-9d53-04cba22f6df9.png)

**Comment by RobRendell** [comment]
It's not just OrbitControls.  Many (perhaps all?) of Drei's components appear to have Typescript types with all their props marked as required, whether they're optional or not.  I get hundreds of warnings from my IDE whenever I commit.

```
Warning:(51, 14) Element Line doesn't have required attribute clipping
Warning:(51, 14) Element Line doesn't have required attribute userData
Warning:(51, 14) Element Line doesn't have required attribute customProgramCacheKey
Warning:(51, 14) Element Line doesn't have required attribute polygonOffsetUnits
Warning:(51, 14) Element Line doesn't have required attribute precision
Warning:(51, 14) Element Line doesn't have required attribute type
(snip)
```

```
Warning:(27, 10) Element Html doesn't have required attribute getObjectByProperty
Warning:(27, 10) Element Html doesn't have required attribute parent
Warning:(27, 10) Element Html doesn't have required attribute userData
Warning:(27, 10) Element Html doesn't have required attribute setRotationFromQuaternion
Warning:(27, 10) Element Html doesn't have required attribute type
Warning:(27, 10) Element Html doesn't have required attribute uuid
Warning:(27, 10) Element Html doesn't have required attribute raycast
Warning:(27, 10) Element Html doesn't have required attribute localToWorld
Warning:(27, 10) Element Html doesn't have required attribute rotateOnAxis
(snip)
```

**Comment by juuyan** [comment]
@RobRendell lol...bad to hear that...do you have any workaround?

**Comment by drcmda** [comment]
is this new? it shouldnt be like that - we never got any complaints before. could you look into the types to see what's up?

**Comment by juuyan** [comment]
Yeah its new. And I've checked the source code, yet so far I couldn't find the reason... The props should be all optional according to the typing.... Is there any possible issue might lead to this? 

my local set:

yarn berry

tsconfig:
```
{
  "files": [
    "twin.d.ts"
  ],
  "compilerOptions": {
    "jsx": "preserve",
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "skipLibCheck": true,
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true
  },
  "include": [
    "**/*.ts",
    "**/*.tsx",
    "next-env.d.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by juuyan** [comment]
@drcmda I have done some experiments.
1. The Type OrbitControls works right.
![image](https://user-images.githubusercontent.com/48427014/92309312-0fc81780-efd7-11ea-9f16-55848bcd074f.png)

2. I've tried to define the OrbitControls component locally and it works...
![image](https://user-images.githubusercontent.com/48427014/92309284-d5f71100-efd6-11ea-823b-7f29cd26ac52.png)

**Comment by RobRendell** [comment]
It seems to be a problem with my IDE's intellisense, rather than Typescript - a genuine missing required prop would be an error that would fail Typescript typechecking.

However, it's interesting that it's something about Drei's type definitions which is confusing it, when e.g. react-three-fiber's type definitions are fine.

@juuyan what IDE are you using, where you're getting the warnings?  I'm using IntelliJ Idea, Ultimate edition version 2020.2.1 (latest - I updated to see if it fixed the warning issues).

**Comment by juuyan** [comment]
@RobRendell 
I'm using Vscode @latest
I feel so.  But I have tried with and without eslint, in Yarn Berry and Classic...........all failed......Can't figure out what's wrong. Would it come from some bug in TS compile? i.e. TS cant properly handle some typing in drei

**Comment by stephencorwin** [comment]
I am using vscode with drei `v1.4.0` and am not having any typing issues.
![image](https://user-images.githubusercontent.com/3931162/92330637-5ef56300-f03e-11ea-8767-9917d2f1f7ed.png)
![image](https://user-images.githubusercontent.com/3931162/92330626-500eb080-f03e-11ea-87e8-a5b990e0485f.png)

You can try restarting the typescript server using `CTR/CMD+SHIFT+P` and typing `TypeScript: Restart TS Server`
![image](https://user-images.githubusercontent.com/3931162/92330655-81877c00-f03e-11ea-927f-d4db874a8d21.png)

**Comment by stephencorwin** [comment]
@juuyan @RobRendell Make sure that you **do not** have `@types/three` installed since those types are shipped with three directly now. I know that there are some weird oddities that happen if you have that package installed still.

**Comment by juuyan** [comment]
@stephencorwin hey thanks. Tired and no @types/three.....so weird...😅

**Comment by RobRendell** [comment]
@stephencorwin I *did* have `@types/three` in my packages.json, but removing it didn't address the issue of the spurious warnings about Drei's components.  Thank you for the info though - it's good to clean up unnecessary dependencies!

**Comment by juuyan** [comment]
@stephencorwin I have got it solved by a workaround: install its peer dependency `three` in the root of project. I'm using Yarn Berry + workspaces. Guess it is an issue caused by PnP... Asking for help in Yarn community for a solution..
![image](https://user-images.githubusercontent.com/48427014/92348080-83b40e00-f104-11ea-8259-1435ed1a1252.png)
![image](https://user-images.githubusercontent.com/48427014/92348087-8878c200-f104-11ea-8271-67e7055d04f0.png)

**Comment by stephencorwin** [comment]
@juuyan ah, makes sense. I'm using npm + lerna for my monorepo solution and I had THREE installed in the root already since having multiple THREE instances in the code can cause issues. Thanks for digging and coming back here with the info so others can find this later.

**Comment by RobRendell** [comment]
Unfortunately in my case, I already have three as an explicit dependency in my project.  Oh well.

**Comment by stephencorwin** [comment]
@RobRendell If you're still having issues, we can try to live debug on our discord server:
[![Discord Shield](https://discordapp.com/api/guilds/740090768164651008/widget.png?style=banner2)](https://discord.gg/ZZjjNvJ)

**Comment by RobRendell** [comment]
Well, we established that it was an issue with IntelliJ Idea, rather than my project setup, since vscode didn't have the same issue with Line and Html.  Thanks, @stephencorwin !

I dug into it a bit more, and found that the error is coming from an "HTML missing required attribute" inspection, which the IDE is apparently extending to warn about React component props as well.  Since I'm using Typescript, which will report an error if a required attribute on a React component is missing, I've turned off the HTML inspection, although it's not ideal.

Thanks again!

**Comment by RWOverdijk** [comment]
@RobRendell Did you happen to ever find a more ideal solution?

**Comment by RobRendell** [comment]
@RWOverdijk No, sorry - I turned off the "missing required attribute" HTML inspection, and haven't experimented with any alternatives since.

**Comment by funwithtriangles** [comment]
I'm having the exact same issue with a Netlify build. Works fine locally. If anyone could point me in the right direction on how to solve, that would be great.

**Comment by funwithtriangles** [comment]
Fixed: Had to install `@types/three`. Above in this thread there is a recommendation to not have this installed, although I think that has changed now and types are for three are external...

**Comment by joshuaellis** [comment]
That comment is really outdated. I’ve hidden it now.
