### ISSUE TITLE
[feature] useHelper

### ISSUE THREAD

**Issue by gsimone** [react-spring/drei#12]
I'm using a simple hook to reduce boilerplate when using helpers, let me know if it's something that could be useful:

https://codesandbox.io/s/r3f-usehelper-075y8

**Comment by drcmda** [comment]
let's add it!

**Comment by gsimone** [comment]
Alright, I've made some progress, I'll share here before a pr as I'm not sure about some details.

https://codesandbox.io/s/r3f-use-helper-bm2qu?file=/src/use-helper.tsx

- I'm not sure how to type the arguments to the hook, the second one should be an helper constructor but I can't seem to find any type in threejs that could work for all helpers
- the rest of the arguments would be passed to the constructor, don't know if <any> is the correct way to do it

**Comment by drcmda** [comment]
users should be able to do:

```jsx
useHelper<SpotLightHelper>(ref, SpotLightHelper, color)
```

```jsx
// If **T** contains a constructor, @see ConstructorParameters must be used, otherwise **T**.
type Args<T> = T extends new (...args: any) => any ? ConstructorParameters<T> : T

function useHelper<T>(
  ref: React.MutableRefObject<Object3D>,
  proto: T,
  ...args: Args<T>
) {
```

**Comment by gsimone** [comment]
So, I updated the sandbox with your suggestions, still:

1. 
```
useHelper<BoxHelper>(mesh, BoxHelper, "cyan");
```

gives me a type error "Argument of type 'typeof BoxHelper' is not assignable to parameter of type 'BoxHelper'."

This is fixed using `useHelper<typeof BoxHelper>(...)` ( and I'm not sure if this is desirable)

2. 
in the hook I get these type errors:
`Type 'T' does not satisfy the constraint 'new (...args: any) => any'`
and 
`This expression is not constructable.` when I try to create the new helper instance.

I'm not sure if there is a simpler approach or I'm missing some piece of ts knowledge to make this work

**Comment by drcmda** [comment]
i dont know TS myself, but in reactthreefiber they have solved args in /src/three-types.ts maybe you find something over there

**Comment by gsimone** [comment]
I fixed the warning but I think that made everything too "any"ish, maybe I'll just PR now and open an issue later to have somebody more expert with TS check the typings

**Comment by drcmda** [comment]
that's fine, thats how i do it as well most of the time, eventually it will annoy someone and they fix it ;-)
