### ISSUE TITLE
How to use controlled TransformControls?

### ISSUE THREAD

**Issue by kevinresol** [react-spring/drei#21]
I tried something like this:

```jsx
<TransformControls position={props.position} ref={ref}>
	<mesh position={props.position}>
		{/* geometry and material omitted for brevity */}
	</mesh>
</TransformControls>
```

and fire a callback like so:

```js
ref.current.addEventListener('dragging-changed', function(e) {
  props.onChange(ref.current.object.position);
});
```

but when the position is updated and the view re-rendered, the mesh and the UI helper will jump away for the same distance of the last drag. My gut feeling is that there are some internal offset stored by the control which breaks this controlled pattern.

**Comment by drcmda** [comment]
i dont know how transformcontrols works internally, but is it even possible to control them? they're for certain not made for react.

**Comment by kevinresol** [comment]
> but is it even possible to control them

Apparently it doesn't right now. But I guess it could be done if transformcontrols expose some functions to reset its internally cached state.
