### ISSUE TITLE
'document is undefined' with SSR

### ISSUE THREAD

**Issue by cdebotton** [react-spring/drei#23]
When importing drei in an app that renders with SSR, an error is thrown as `troika-3d-text` has multiple references to the `document` object. This can be circumvented by loading components that require this using lazy or dynamic imports, but unfortunately, importing _anything_ from `drei` will bring in `troika-3d-text`, so it is impossible to, for example, use the awesome `<HTML />` component for a loading state for the modules we want to lazy load that contain these `document` references.

Here is the full error:

```
Server Error
ReferenceError: document is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///Users/me/www/cdb/node_modules/troika-3d-text/dist/textmesh-standalone.umd.js (4285:16)
<unknown>
file:///Users/me/www/cdb/node_modules/troika-3d-text/dist/textmesh-standalone.umd.js (2:66)
Object.<anonymous>
file:///Users/me/www/cdb/node_modules/troika-3d-text/dist/textmesh-standalone.umd.js (5:2)
Module._compile
internal/modules/cjs/loader.js (955:30)
Object.Module._extensions..js
internal/modules/cjs/loader.js (991:10)
Module.load
internal/modules/cjs/loader.js (811:32)
Function.Module._load
internal/modules/cjs/loader.js (723:14)
Module.require
internal/modules/cjs/loader.js (848:19)
require
internal/modules/cjs/helpers.js (74:18)
Object.troika-3d-text/dist/textmesh-standalone.umd
webpack:///external%20%22troika-3d-text/dist/textmesh-standalone.umd%22 (1:0)
__webpack_require__
webpack:///webpack/bootstrap (27:0)
Object../node_modules/drei/dist/index.cjs.js
node_modules/drei/dist/index.cjs.js (19:29)
__webpack_require__
webpack:///webpack/bootstrap (27:0)
Module../src/pages/index.tsx
file:///Users/me/www/cdb/.next/server/static/development/pages/index.js (55469:62)
__webpack_require__
webpack:///webpack/bootstrap (27:0)
Object.3
file:///Users/me/www/cdb/.next/server/static/development/pages/index.js (55642:18)
```

**Comment by drcmda** [comment]
it should tree-shake. i've tried it, just using HTML and there is no mention of troika in the resulting bundle. are you in dev mode perhaps, or is there any other reason why it wouldn't shake off un-used dependencies?

**Comment by cdebotton** [comment]
Thanks for the quick reply! Embarrassingly, I didn’t consider I was in dev mode, but I’m still wondering if there’s a preferred way to work with these tools while developing an application as any page that imports drei will throw an error.

**Comment by drcmda** [comment]
He fixed it, could you try loading this lib in ssr? https://github.com/protectwise/troika/issues/46 we're not sure if that's all that we need to do

**Comment by cdebotton** [comment]
@drcmda Thanks for the follow-up! The undefined `document` errors are gone, I am however seeing this is in my console when running the app:

```
Troika createWorkerModule: web workers not allowed in current environment; falling back to main thread execution. ReferenceError: Worker is not defined
    at supportsWorkers (/Users/me/www/cdb/node_modules/troika-worker-utils/dist/troika-worker-utils.umd.js:417:20)
    at defineWorkerModule (/Users/me/www/cdb/node_modules/troika-worker-utils/dist/troika-worker-utils.umd.js:472:10)
    at /Users/me/www/cdb/node_modules/troika-worker-utils/dist/troika-worker-utils.umd.js:606:30
    at /Users/me/www/cdb/node_modules/troika-worker-utils/dist/troika-worker-utils.umd.js:2:66
    at Object.<anonymous> (/Users/me/www/cdb/node_modules/troika-worker-utils/dist/troika-worker-utils.umd.js:5:2)
```

It doesn't prevent the app from rendering, which is great, but it does add noise to logs.

**Comment by drcmda** [comment]
could you open a new ticket over there (troika)? there's nothing i can do here, other than messing with the build system, but would be great to keep the flatbundle for convenience.

**Comment by sovetski** [comment]
I am getting the same error and it looks coming from `useLoader`
