### ISSUE TITLE
Pass ref to OrbitControls

### ISSUE THREAD

**Issue by Pomevak** [react-spring/drei#24]
When I pass ref to OrbitControls, `ref.current`does not return the object immediately after the component mounted, it takes a while for `ref.current` to evaluate to OrbitControls. This is confusing me and I think this might be a bug?
```
React.useEffect(() => {
    console.log(ref.current) // undefined
    setTimeout(()=>console.log(ref.current), 2000) // OrbitControls
  }, [])
```

**Comment by drcmda** [comment]
it works as i would expect it to: https://codesandbox.io/s/r3f-contact-shadow-bkt7n

maybe you have it inside a Suspense block or anything else that makes it appear async. but if it's in a normal component it's guaranteed to be filled in useEffect.

**Comment by Pomevak** [comment]
> it works as i would expect it to: https://codesandbox.io/s/r3f-contact-shadow-bkt7n
> 
> maybe you have it inside a Suspense block or anything else that makes it appear async. but if it's in a normal component it's guaranteed to be filled in useEffect.

I see. I am using SSR, so I have to dynamically import the component. Maybe that's the cause of the problem. But do you have any suggestions on how I can solve this problem? Thanks a lot.
