### ISSUE TITLE
Stopped working with SSR since 0.32 => 0.33

### ISSUE THREAD

**Issue by crubier** [react-spring/drei#25]
While all version of drei <= 0.32 work with Server Side Rendering, all verion >= 0.33 fail in Gatsby (and I supposed most Server Side Rendering solutions) with this error:

```
failed Building static HTML for pages - 10.964s

 ERROR #95312 

"document" is not available during server-side rendering.

See our docs page for more info on this error: https://gatsby.dev/debug-html


> 1 | import _inheritsLoose from '@babel/runtime/helpers/inheritsLoose';
    | ^
  2 | import { createContext, forwardRef, createElement, Component, Fragment } from 'react';
  3 | import createCache from '@emotion/cache';
  4 | import { getRegisteredStyles, insertStyles } from '@emotion/utils';


  Error: WebpackError: ReferenceError: document is not defined
  
  - core.esm.js:1 
    [@emotion-core-npm-10.0.28-490246e9e8-2.zip]/[@emotion]/core/dist/core.esm.js:1:1

```

This seems to be related to the introduction of `troika`, I think troika uses `document` with no checks, failing on server side.

**Comment by drcmda** [comment]
i believe this could be related to https://github.com/react-spring/drei/issues/23 there should not be a trace of troika in the bundle if you dont use it. otherwise i think we have to open a ticket on troikas GH.

**Comment by drcmda** [comment]
Could you try his fix out https://github.com/protectwise/troika/issues/46 ?

**Comment by gsimone** [comment]
Closing since it's a bunch of versions ago. Please reopen if it's still an issue with the latest version 👍
