### ISSUE TITLE
Possible to Apply StandardEffect to Specific Mesh or Group

### ISSUE THREAD

**Issue by reggie3** [react-spring/drei#26]
Is it possible to apply the StandardEffect to a specific mesh or group?  I'm trying to apply the bloom effect to a specific item in a scene.

**Comment by drcmda** [comment]
Look for react-postprocessing this will all be possible with it

**Comment by gsimone** [comment]
https://github.com/react-spring/react-postprocessing 
Leaving the link to the repo for future reference

**Comment by reggie3** [comment]
Thanks for pointing that out.  Here's a link to a Codesandbox that use's that library https://codesandbox.io/s/react-post-processing-single-item-3dm54?file=/src/index.js
I'm running into an issue with it, but I'll post it with that library.

New issue: https://github.com/react-spring/react-postprocessing/issues/3
