### ISSUE TITLE
Add a storybook for examples/development

### ISSUE THREAD

**Issue by gsimone** [react-spring/drei#28]
We could move all the examples from codesandbox to a storybook hosted on netlify, or a maybe even a cra.

On one hand it would be a nice way to collect examples, on the other it would give a good dev env.

**Comment by gsimone** [comment]
I'm starting to work on it in my fork, let me know if it's something worth adding 

https://github.com/gsimone/drei

preview: https://focused-meninsky-e3f9e4.netlify.app/

**Comment by drcmda** [comment]
looks nice! does it have something that lists props as well, so that we could use as an interactive documentation? you can make the pr

**Comment by gsimone** [comment]
Yes, there are some add-ons that can do that, it'll have to wait a bit since Me and my computer need some repairs - butterfly keyboard and wrist lol

**Comment by gsimone** [comment]
I'll close this, I opened the draft PR https://github.com/react-spring/drei/pull/34
