### ISSUE TITLE
Follow up #21 & #27

### ISSUE THREAD

**Issue by kevinresol** [react-spring/drei#29]
For #27, Sorry the alternative destructure strategy is actually problematic:

because it now passes undefined values to the transform control, e.g. `enabled={undefined}`, or `showX={undefined}`, causing very weird errors. Not expert of TS, is there a way to not pass undefined props to the control?

**Comment by gsimone** [comment]
I'm not sure if I'm misunderstanding, but I think you could use something like pick 
 and omit from lodash https://lodash.com/docs/4.17.15#pick

```js
import pick from "lodash.pick";
import omit from "lodash.omit";

const props = {
  showX: true,
  position: [1,2,3]
};

const transformOnlyPropNames = ["showX", "enabled"];

const transformProps = pick(props, transformOnlyPropNames);  // {showX: true}
const objectProps = omit(props, transformOnlyPropNames); // {position: Array[3]}
```

https://codesandbox.io/s/magical-villani-zfzlo?file=/src/index.js:0-334

**Comment by drcmda** [comment]
merged the pr, published, too
