### ISSUE TITLE
Frame blue when I use Orbitcontrols

### ISSUE THREAD

**Issue by cristianvj** [react-spring/drei#39]
Hello everyone, when I use OrbitControls and I make click on the 3D object, appear a blue frame. I need to remove it. Thanks

**Comment by drcmda** [comment]
not sure what you mean, please make a very reduced codesandbox. its probably just css focus from how it sounds.

**Comment by gsimone** [comment]
It's the canvas element getting focus, it only happens when using OrbitControls

**Comment by cristianvj** [comment]
Hello, excuse me for responding late. Watch this example and clic on the object so you see a blue focus around the canvas. [Example here](https://codesandbox.io/s/r3f-contact-shadow-tio14?file=/src/index.js)

![Screen Shot 2020-06-23 at 2 12 58 PM](https://user-images.githubusercontent.com/18078281/85449532-7784cf80-b55d-11ea-9bc0-72a310943e22.png)

**Comment by cristianvj** [comment]
I know that I can remove with CSS, but is important prevent it from appearing by default.
```
 *:focus {
  outline: none;
}
```
