### ISSUE TITLE
OrbitControl typings don't allow passing target as array

### ISSUE THREAD

**Issue by neefrehman** [react-spring/drei#40]
I've just moved a project to TypeScript and have noticed that in the `target` prop for `OrbitControls` I can no longer pass an array due to typings. I now have to import `Vector3` from `three` instead.

Old way (JS only):
```js
<OrbitControls target={[0, 0, 0]} />
```

Workaround (TS):
```js
import { Vector3 } from "three";
...

<OrbitControls target={new Vector3(0, 0, 0)} />
```

While the workaround is simple, it would be nice to accept an array in TS for parity. I'm assuing that the solution will be similar to this one from R3F: https://github.com/react-spring/react-three-fiber/issues/208

**Comment by drcmda** [comment]
should be fixed

**Comment by neefrehman** [comment]
confirmed working. thanks!
