### ISSUE TITLE
Request: Add a <BackgroundPlane/>

### ISSUE THREAD

**Issue by Fasani** [react-spring/drei#42]
Reminder to myself to add a full-size background plane component.

https://gist.github.com/pfreema1/091b088481deca42b88d3f83f13cf1b8

**Comment by Fasani** [comment]
Sorry, I am a noob, this is technically covered by `useAspect()` already, so it is not needed.

```
import React from 'react';
import { useAspect } from 'drei';

export default function Background(props) {
    const scale = useAspect('cover', 1, 1, 2);

    return (
        <mesh {...props} scale={scale}>
            <planeGeometry attach="geometry" />
            <meshPhongMaterial attach="material" color="grey" />
        </mesh>
    );
}
```

**Comment by gsimone** [comment]
Well, you gave a me a good idea for the `useHelper` storybook lol

**Comment by drcmda** [comment]
@Fasani if its really just about fullscreen, if the aspect doesnt matter, then this will do as well:

```jsx
const { viewport } = useThree()
return <mesh scale={[viewport.width, viewport.height, 1]} ... />
```

**Comment by Fasani** [comment]
Thanks @drcmda 

Then I discover that I need to do `height * window.devicePixelRatio` or the plane area does not fill the screen, is this expected? Also, I did not see r3f setting `.setPixelRatio()` so now wonder if I should do this manually to make a crisper canvas?  (if I understood this `setPixelRatio` correctly...).

**Comment by gsimone** [comment]
I added this example to the storybook https://drei-storybook-beta.netlify.app/?path=/story/misc-useaspect--texture-story 
Is this what you had in mind?

**Comment by drcmda** [comment]
> Then I discover that I need to do `height * window.devicePixelRatio` or the plane area does not fill the screen, is this expected? Also, I did not see r3f setting `.setPixelRatio()` so now wonder if I should do this manually to make a crisper canvas? (if I understood this `setPixelRatio` correctly...).

```jsx
<Canvas pixelRatio={window.devicePixelRatio} ... />
```

you can get pixelration like so

```jsx
const { gl } = useThree()
gl.getPixelRatio()
```

but indeed, it looks like i didnt take it into account for the viewport. if you want to try it it's in `getCurrentViewport` in canvas.tsx. but it should work for both ortho and persp cameras. not sure if we also have to multiple PR in ortho mode?

**Comment by Fasani** [comment]
I will check + add it.. I need to start getting hands dirty in TypeScript.

**Comment by Fasani** [comment]
@drcmda just a quick question about your `drei` / `react-three-fiber` workflow.

I made some `pixelRatio` changes in the `v5` branch in the `canvas.tsx` file. I have a demo project locally where I can test this pretty quickly so my current process is to run `npm run build` and then just directly reference the new build in my project.

Just wondering how do you usually build/test new `drei` components today or how do you build/test `v5` changes, how is your set up to allow rapid development and testing, building the repo each time feels a little slow.

**Comment by gsimone** [comment]
> @drcmda just a quick question about your `drei` / `react-three-fiber` workflow.
> 
> 
> 
> I made some `pixelRatio` changes in the `v5` branch in the `canvas.tsx` file. I have a demo project locally where I can test this pretty quickly so my current process is to run `npm run build` and then just directly reference the new build in my project.
> 
> 
> 
> Just wondering how do you usually build/test new `drei` components today or how do you build/test `v5` changes, how is your set up to allow rapid development and testing, building the repo each time feels a little slow.

The answer to this question should be added to a contribution guide

**Comment by Fasani** [comment]
I agree! I’m happy to be the first consumer  and fill in the gaps and put it in the wiki 😍

**Comment by gsimone** [comment]
Btw for drei I use the storybook, just import the new stuff in a story and work on it like a regular dev server.

**Comment by Fasani** [comment]
I spent the evening looking into `npm link` and then `yarn link` but neither really helped me. I then found this (https://github.com/FormidableLabs/lank) which seems cool but again with no real success (yet). Time to hit the sack.

**Comment by drcmda** [comment]
R3f examples uses cra-rewired and an alias into source, so you can debug directly

**Comment by Fasani** [comment]
@drcmda further investigation on this topic, in the end, the pixel ratio is not needed to calculate the viewport. Ths issue I had was a silly one, I had the plane wrapped in a container which had a z position of -5. Obviously this made it look like the panel was not big enough but when setting the panel to have a position of 0 in the Z then it works as expected even when you change pixel ratio.
