### ISSUE TITLE
<HTML> is not PascalCase

### ISSUE THREAD

**Issue by neftaly** [react-spring/drei#43]
`<HTML>` primitives throw the following linting error with default standard/semistandard(/eslint?) config:

```
error  Imported JSX component HTML must be in PascalCase  react/jsx-pascal-case
```

Is it possible to rename `<HTML>` back to `<Dom>` (as was in r3f) or similar?

**Comment by neftaly** [comment]
I'm happy to make a PR for this BTW

**Comment by drcmda** [comment]
better use import { HTML as Html } for now on. changing the name again after changing repos would confuse the hell out of people. i wasnt aware of that rule :-S

**Comment by gsimone** [comment]
We could keep supporting HTML with a warning and alias it to Html ( while referring to Html in the docs )

**Comment by drcmda** [comment]
That would also work ...

**Comment by neftaly** [comment]
Would it be better to rename this to `<View>`, for future RN support?
