### ISSUE TITLE
Add a draw-helper prop to cameras

### ISSUE THREAD

**Issue by HKalbasi** [react-spring/drei#44]
CameraHelper in three js is a very good thing for debugging cameras. It does not play well with react-three-fiber because it need camera as its parameter. Adding a draw-helper prop to camera components in drei could solve this problem. When we need to debug our camera, we can set
```<Camera makeDefault={false} defaultHelper={true}/>``` and we can see and debug the camera.

**Comment by gsimone** [comment]
You could try with `useHelper`, something like

```jsx
import {useHelper} from 'drei'
import * as THREE from 'three'

const A = () => {
  
   const camera = useRef()

   useHelper(THREE.CameraHelper, camera)

   return <Camera ref={camera} />
}
```

**Comment by gsimone** [comment]
You can take a look at a code example here: https://drei-storybook-beta.netlify.app/?path=/story/misc-usehelper--camera-story

**Comment by HKalbasi** [comment]
Seems good enough. Thank you.
