### ISSUE TITLE
Can't import in node.js

### ISSUE THREAD

**Issue by flyon** [react-spring/drei#50]
I'm having trouble importing this module for code that runs both on the server as well as in the browser (through a webpack bundle).

I'm imorting things like this: 
import { HTML } from "drei";

Which results in an error:

```
node_modules\three\examples\jsm\controls\OrbitControls.js:10
import {
SyntaxError: Unexpected token {
```

Any way to import this library in node without it resulting in errors?

**Comment by drcmda** [comment]
jsm is from threejs, they have untransipiled import statement. if you use node you can transpile or use a node version that understands imports.

**Comment by flyon** [comment]
Thank you for the reply. 
I run the latest version of node. Also doesn't work with --experimental-models flag or "type" : "module" in package.json.

I would understand if you cant help with this, but my question would be: I would transpile drei & three .. put the output in my own folder and include that? It just seems a bit weird to transpile from node_modules

**Comment by drcmda** [comment]
i have never used next but im sure this problem must come up often as import statements become normalized. otherwise i think there's nothing that we can do here. orbitcontrols is a threejs feature and their export. without the drei wrapper that makes it easier to use you'd run into the same problem. but i would still suggest opening an issue on their tracker, they also must've have come across this once or twice.

**Comment by huntercaron** [comment]
Also running into this with nextjs – bit of a shame as next is probably the easiest / most minimal react website setup with well supported fast refresh right now but I couldn't find a solid issue / PR

Current fix that worked for me 
`yarn add next-transpile-modules`

then add a `next.config.js` in your root dir if you don't have one already
```
// next.config.js
const withTM = require("next-transpile-modules")([
    "drei",
    "three",
    "postprocessing",
]) // pass the modules you would like to see transpiled

module.exports = withTM()
```

Will take a sec on the first run to transpile everything but it all seems to work.
Also if you're looking for an alternative - gatsby doesn't have this issue

**Comment by huntercaron** [comment]
Also running into this with next - not sure if you're using next as well but the solution does seem to be transpilling for now

Current fix that worked for me 
`yarn add next-transpile-modules`

then in `next.config.js`
```
// next.config.js
const withTM = require("next-transpile-modules")([
    "drei",
    "three",
    "postprocessing",
]) // pass the modules you would like to see transpiled

module.exports = withTM()
```

Will take a sec on the first run to transpile everything but it all seems to work.

**Comment by gsimone** [comment]
I'll make a PR to update the three-js example
