### ISSUE TITLE
How to start/stop audio using PositionalAudio? 

### ISSUE THREAD

**Issue by Franckapik** [react-spring/drei#51]
Hi,
Thank you for this library !
I was wondering what is the way to start/stop audio with PositionalAudio? 
Here is my code  : 

```
const Audio = (props) => {

  return (
    <mesh {...props}>
    <boxBufferGeometry attach="geometry" />
    <meshBasicMaterial attach="material" color="hotpink" />
    <PositionalAudio url={props.url} distance={0.5} loop={false}  />
  </mesh>
  )
}

export default Audio
```

**Comment by drcmda** [comment]
if you put a ref on it you get the threejs class, you can call all the methods that it has. but from what i thought PA starts/stops when objects come near the threshold.

**Comment by Franckapik** [comment]
That's right! I'm sorry if i have not thinked about the ref on PositionalAudio ... I will find a way to change the audio file with URL to allow a kind of playlist with it ... Thank you again!
