### ISSUE TITLE
[Documentation] HTML scaleFactor prop

### ISSUE THREAD

**Issue by RobRendell** [react-spring/drei#52]
It would be nice if the doco for the scaleFactor prop of the HTML component mentioned that the HTML element is also scaled based on the distance to a PerspectiveCamera, but not for an OrthographicCamera or if scaleFactor is undefined.

**Comment by drcmda** [comment]
could you make a pr for correct wording? my germany english is a complete mess :-(

**Comment by RobRendell** [comment]
Ok, PR created.  See what you think.

And your English is fine - a heck of a lot better than my German!

Danke schoen :)
