### ISSUE TITLE
Add shortcuts for common loaders

### ISSUE THREAD

**Issue by gsimone** [react-spring/drei#53]
These could be useful to simplify common loader use-cases, having to import from examples is counter-intuitive.

```jsx
import { useGLTF, useTexture } from 'drei'

...

const gltf = useGLTF("./Fox.bin", { draco: true })
const texture = useTexture("./texture.png")
```

**Comment by drcmda** [comment]
seems like a good idea! you can go ahead, im tired of typing the examples/jsm stuff for real 😄
