### ISSUE TITLE
unnecessary horizontal scrollbar

### ISSUE THREAD

**Issue by jarjav** [react-spring/drei#54]
if fullscreen prop is added to HTML tag
 
`<HTML fullscreen ... />`

and content height is bigger than 100vh, horizontal scrollbar appeared (because of vertical scrollbar)

I think that horizontal scrollbal is unnecessary and not pretty because of content width is less than 100%

**Comment by drcmda** [comment]
it should have overflow: hidden, is that correct?

**Comment by jarjav** [comment]
no 

`<HTML fullscreen style={{ overflow: "hidden" }} ...>` does not work as expected 

your example at https://codesandbox.io/s/r3f-contact-shadow-jvssp (I try implement in my project)
also has horizontal scrollbar

**Comment by jarjav** [comment]
Because overflow: hidden hide both scrollbars overflowX is necessary instead of overflow.
Also in your example is place to add overflowX not HTML tag, but scrollArea div. 
 
Here is solution I find:
```
<div
   className="scrollArea"
   ref={scrollArea}
   onScroll={onScroll}
   style={{ overflowX: "hidden" }}
   {...events}
>
   <div style={{ position: "sticky", top: 0 }} ref={domContent} />
   <div style={{ height: `${state.pages * 100}vh` }}/>
</div>
```
