### ISSUE TITLE
<Line /> Codesandbox example is broken

### ISSUE THREAD

**Issue by m9dfukc** [react-spring/drei#56]
The codesandbox example for `<Line />` results in several errors and won't show any output ... 

```
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at index.js:14.
```

**Comment by giulioz** [comment]
It was because the sandbox used an older version of Drei with wrong exports. It should be fixed now.

<img width="1058" alt="immagine" src="https://user-images.githubusercontent.com/1353142/87221253-d5415600-c36a-11ea-9d20-5173cda49aca.png">
