### ISSUE TITLE
UMD and CJS imports cause errors when using drei with vite

### ISSUE THREAD

**Issue by gsimone** [react-spring/drei#57]
Webpack works around this problem, might be worth fixing.

https://twitter.com/youyuxi/status/1282767177259659265

Repro: https://github.com/stolinski/vite-test

**Comment by kennetpostigo** [comment]
I've ran into this with Next.js as well, I ended up having to use the nextjs transpile plugin, but it was a lot of pain to figure that out. had to do with imports from `jsm` folder in threejs from drei internals

**Comment by drcmda** [comment]
i think this is fixed now

**Comment by gsimone** [comment]
Yes, everything works as expected now https://github.com/gsimone/vite-test 👍
