### ISSUE TITLE
Attempted import error: 'addAfterEffect' is not exported from 'react-three-fiber'.

### ISSUE THREAD

**Issue by n1ru4l** [react-spring/drei#59]
I am experiencing this issue with create-react-app when building for production:

```

Creating an optimized production build...
Failed to compile.

./node_modules/drei/dist/index.js
Attempted import error: 'addAfterEffect' is not exported from 'react-three-fiber'.
```

```
    "drei": "0.0.63",
    "react-three-fiber": "4.2.12",
    "three": "0.118.3",
```

**Comment by n1ru4l** [comment]
Fixed by upgrading to `react-three-fiber@4.2.17`

**Comment by neefrehman** [comment]
It might be worth reopening this issue as I've just discovered it exists on the `react-three-fiber` 5.0 beta.

i can see the only import of `addAfterEffect` from r3f comes from the `Stats` component.

**Comment by drcmda** [comment]
you mean it does not exist for 5.0 beta?

**Comment by neefrehman** [comment]
sorry, this import error exists in the beta, because `addAfterEffect` does not

**Comment by drcmda** [comment]
published a new beta
