### ISSUE TITLE
Updating Text content

### ISSUE THREAD

**Issue by n1ru4l** [react-spring/drei#62]
I have the following node:

```tsx
<Text
  anchorX="center"
  anchorY="middle"
  fontSize={0.8 * initialRadius}
  color="black"
  font={buildUrl("/fonts/Roboto-Bold.ttf")}
>
  {props.textLabel}
</Text>
```

When the text changes I only see the first character of the new text appearing. The other ones are invisible, the character is still positioned as if the other characters would be present.

When adding a key property to the Text element with the contents of the props.textLabel this issue is resolved. However, I assume this is some kind of a bug and changing the children text should update the text without having to set a `key`.

**Example**:

![IMG_B45935046C3F-1](https://user-images.githubusercontent.com/14338007/88140762-9d4fd380-cbf2-11ea-97ad-bf63fedd3afa.jpeg)

The purple token text has been updated from `B` to `asdas`

**Comment by n1ru4l** [comment]
This might be related to https://github.com/protectwise/troika/blob/master/packages/troika-three-text/CHANGELOG.md#bug-fixes

**Comment by drcmda** [comment]
the way text works internally is a bit unfortunate. in threejs mutation and cloning is normal, but in reacts immutable world that causes problems. this component seems to have some trouble updating. anyway, i have refreshed dependencies and published a new patch.

**Comment by n1ru4l** [comment]
Okay I updated to 0.0.64 and now I have the issue that the other texts disappear when changing another text.

**Comment by drcmda** [comment]
could you try with plain troika and see if you figure out a solution?

this is the wrap that drei publishes

```jsx
import React, { Children, createElement, forwardRef, useMemo, useRef, useLayoutEffect, useState } from 'react'
import { Text as TextMeshImpl } from 'troika-three-text'
import { extend } from 'react-three-fiber'
import mergeRefs from 'react-merge-refs'

extend({ TextMeshImpl })

export const Text = forwardRef(({ anchorX = 'center', anchorY = 'middle', children, ...props }, ref) => {
  const textRef = useRef()
  const [baseMtl, setBaseMtl] = useState()
  const [nodes, text] = useMemo(() => {
    let n: React.ReactNode[] = []
    let t = ''
    Children.forEach(children, (child) => {
      if (typeof child === 'string') t += child
      else if (child && typeof child === 'object' && child.props.attach === 'material') {
        // Instantiate the base material and grab a reference to it, but don't assign any
        // props, and assign it as the `material`, which Troika will replace behind the scenes.
        n.push(createElement(child.type, { ref: setBaseMtl, attach: 'material' }))
        // Once the base material has been assigned, grab the resulting upgraded material,
        // and apply the original material props to that.
        if (baseMtl) {
          n.push(<primitive object={textRef.current.material} {...child.props} attach={null} />)
        }
      } else n.push(child)
    })
    return [n, t]
  }, [children, baseMtl])
  useLayoutEffect(() => void textRef.current.sync())

  return (
    <textMeshImpl ref={mergeRefs([textRef, ref])} text={text} anchorX={anchorX} anchorY={anchorY} {...props}>
      {nodes}
    </textMeshImpl>
  )
})
```

you could copy this into a local file for testing. if you find something a PR would be very welcome!

**Comment by n1ru4l** [comment]
I also get the following warning on chrome when the text is updated for the first time:

```
WebGL: INVALID_OPERATION: drawElementsInstanced: no buffer is bound to enabled attribute
renderInstances @ three.module.js:16994
WebGLRenderer.renderBufferDirect @ three.module.js:25564
renderObject @ three.module.js:25993
renderObjects @ three.module.js:25965
WebGLRenderer.render @ three.module.js:25766
renderGl @ web.js:70
(anonymous) @ web.js:85
renderLoop @ web.js:82
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
requestAnimationFrame (async)
renderLoop @ web.js:89
WebGL: too many errors, no more errors will be reported to the console for this context.
requestAnimationFrame (async)
renderLoop @ web.js:89
three.module.js:16994 WebGL: too many errors, no more errors will be reported to the console for this context.

**Comment by n1ru4l** [comment]
Cannot reproduce it either -.- https://codesandbox.io/s/troika-3d-text-via-react-three-fiber-94sv3?file=/src/index.js

**Comment by n1ru4l** [comment]
Maybe @lojjic has an idea

**Comment by lojjic** [comment]
@n1ru4l Thanks -- I'm able to reproduce the new bug in your codesandbox, if I make the text length change on update.

This is definitely related to my attempted fix/workaround in https://github.com/protectwise/troika/issues/69. Three.js changed some internals that broke how I update the geometries, and it looks like my attempted workaround caused this new disappearing text bug. I will fix it and publish a patch release ASAP.

**Comment by n1ru4l** [comment]
@lojjic awesome 😍 thanks for the fast response!

**Comment by lojjic** [comment]
OK, `troika-three-text` 0.30.2 should fix the disappearing text issue.

**Comment by n1ru4l** [comment]
@lojjic Yes it works as expected 🎉 After bumping the version here to 0.30.2 I think we can close this issue! @drcmda Could you push the v0.0.64 changes? Then I could create a pull request for bumping the version

**Comment by n1ru4l** [comment]
Drei now uses `^0.30.2` so this issue can be closed.

https://github.com/react-spring/drei/blob/a752de0405eec8fb3d79115c53c192ec8337a284/package.json#L58
