### ISSUE TITLE
StandardEffects Ambient Occlusion glitch on iOS

### ISSUE THREAD

**Issue by crubier** [react-spring/drei#8]
Ambient occlusion gives this glitch on iOS. 

![675A4759-A6B8-4C54-AD49-DCEC775001E7](https://user-images.githubusercontent.com/2954572/81042733-aad5a700-8ea8-11ea-9f30-be8f53c8e1eb.png)

**Comment by drcmda** [comment]
it's a bug in the postprocessing lib, could you forward it?

here's the pp config that i use: https://github.com/react-spring/drei/blob/master/src/StandardEffects.ts

and it can be overwritten by doing:


```jsx
<StandardEffects ao={{
  opacity: 1,
  blendFunction: BlendFunction.SCREEN,
  kernelSize: KernelSize.VERY_LARGE,
  luminanceThreshold: 0.9,
  luminanceSmoothing: 0.07,
  height: 600,
  }} />
```

**Comment by drcmda** [comment]
could you check again, and maybe try out what @vanruesc recommends here https://github.com/vanruesc/postprocessing/issues/199 ?

**Comment by gsimone** [comment]
Closing this since it's dated, please reopen if it's still a problem with the latest version
