### ISSUE TITLE
event.stopPropagation() not working with Html 

### ISSUE THREAD

**Issue by ivnaleta** [react-spring/drei#80]
Hi.
I want to create some popup over another mesh with <Html>. It works, but click event  fired twice - first in popup div and second in mesh under it.
I tried event.stopPropagation() on first event but it didn't work.
Example - https://codesandbox.io/s/event-propagation-from-html-f0t4v?file=/src/index.js
(if red div box is clicked there are two messages in console - one from div box and one from mesh)
```
function Content() {
  const onMeshClick = e => {
    console.log("mesh clicked")
  }

  const onHtmlClick = e => {
    e.preventDefault()
    e.stopPropagation()
    console.log("html clicked")
  }

  const onDivClick = e => {
    e.preventDefault()
    e.stopPropagation()
    console.log("div clicked")
  }

  return (
    <Canvas>
      <ambientLight />
      <Plane args={[5, 5]} onClick={onMeshClick}>
        <meshBasicMaterial attach="material" color="green" />
      </Plane>
      <Html onClick={onHtmlClick}>
        <div style={{ width: "40px", height: "40px", backgroundColor: "red" }} onClick={onDivClick} />
      </Html>
    </Canvas>
  )
}

```

**Comment by drcmda** [comment]
this is because the html renders somewhere within the canvases parent div, it cant stop the propagation. if you portal html content in front of the canvas, then you can: https://codesandbox.io/s/event-propagation-from-html-pchhd?file=/src/index.js

**Comment by ivnaleta** [comment]
> this is because the html renders somewhere within the canvases parent div, it cant stop the propagation. if you portal html content in front of the canvas, then you can: https://codesandbox.io/s/event-propagation-from-html-pchhd?file=/src/index.js

thanks
