### ISSUE TITLE
Selectable Text: Is there a way to disable it? 

### ISSUE THREAD

**Issue by robksawyer** [react-spring/drei#81]
I'd like to be able to disable the text selection feature of the troika text. Possible?

**Comment by lojjic** [comment]
@robksawyer Can you clarify what you mean by "text selection feature"? There is some base support for caret positions in troika-three-text, but unless there's a bunch of extra logic in `drei` that's making use of that data to perform selection of ranges (which I don't see) then there's no "text selection" implemented per se.

**Comment by robksawyer** [comment]
Actually, I think my issue was something else. I'm noticing that the troika text isn't selectable by default.
