### ISSUE TITLE
simple TypeScript error in dist/MeshDistortMaterial.d.ts

### ISSUE THREAD

**Issue by danielacorner** [react-spring/drei#82]
Hiya,

When installing & trying to use drei in my react project, I get a type error:

![image](https://user-images.githubusercontent.com/9141196/89309605-9c329380-d641-11ea-8967-7abebd72305a.png)

I managed to fix it in my node_modules like this:

![image](https://user-images.githubusercontent.com/9141196/89309560-8ae98700-d641-11ea-80b3-16f8cb7a23f7.png)

Hope that helps!

**Comment by drcmda** [comment]
@gsimone

**Comment by gsimone** [comment]
Do materials in threejs have a transparency prop? I know there's transparent and opacity but can't recall transparency. Could it be a new prop that is missing in the types?

**Comment by stephencorwin** [comment]
There is a `transparent` prop, but it doesn't look like there is a `transparency` one.
https://threejs.org/docs/index.html#api/en/materials/Material.transparent

**Comment by drcmda** [comment]
yes, there was, but it was recently changed to transmission i think.
