### ISSUE TITLE
TransformControls apply in all directions even with some axis disabled

### ISSUE THREAD

**Issue by thedrumz** [react-spring/drei#85]
I'm implementing transformControls but even when I disable some axis it still transforming in this direction. You can test it in this fiddle https://codesandbox.io/s/r3f-drei-transformcontrols-0ngho?file=/src/index.js if you drag from the center of the gizmo the rotation applies in all directions
But I was testing your storybook and this problem is solved https://drei-storybook.netlify.app/?path=/story/controls-transformcontrols--transform-controls-lock-st

**Comment by stephencorwin** [comment]
On the left of the codesandbox, the version of drei is still using `0.015`. Click this and change it to the most recent version.
![image](https://user-images.githubusercontent.com/3931162/89787048-d8a33b00-daea-11ea-86f9-f16b2b569e45.png)

**Comment by thedrumz** [comment]
The expected behavior when you disable X and Y axis is that the rotation applies only in Z axis. In fact, the threejs example works like expected https://threejs.org/examples/#misc_controls_transform

**Comment by thedrumz** [comment]
Sorry, you are right, it was a transformControls issue in an older version of threejs, with the new version it's working as expected.
Thanks!
