### ISSUE TITLE
linewidth prop in Line component should be camel case

### ISSUE THREAD

**Issue by gsimone** [react-spring/drei#97]
Can we make an alias to avoid a breaking change?

**Comment by giulioz** [comment]
It's lowercase since it injects into LineMaterial properties directly.
https://github.com/mrdoob/three.js/blob/3a993b4180f5230e1f34a21b30caaff9eb8ac44f/examples/jsm/lines/LineMaterial.d.ts#L28

Unfortunately it's the only one lowercase.
