### ISSUE TITLE
invalidateFrameLoop with drei Text

### ISSUE THREAD

**Issue by jmatsushita** [react-spring/drei#99]
Hi there, I'm trying to use invalidateFrameLoop with drei Text but as you can see here https://codesandbox.io/s/r3f-invalidate-frameloop-drei-text-x5ndk?file=/src/index.js the Text doesn't display on the first frame. 

Could there be something going on because [`sync()` is asynchronous](https://github.com/protectwise/troika/blob/master/packages/troika-three-text/src/Text.js#L259) and `useLayoutEffect()` expects a synchronous function?

I tried with `troika-three-text` directly https://codesandbox.io/s/troika-3d-text-via-react-three-fiber-invalidateframeloop-c5i7p but the problem is here still, so it might be something more subtle with the asynchronous interaction of react and troika? Is that a use case for `<Suspense>`?

**Comment by giulioz** [comment]
https://codesandbox.io/s/troika-3d-text-via-react-three-fiber-invalidateframeloop-forked-g7r24?file=/src/index.js

Calling `invalidate` after sync solves the issue. I'm making a fix, thanks for pointing this out.

**Comment by jmatsushita** [comment]
Makes sense. Thanks!
